spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none

weapons:
  types:
    1: rock
    2: paper
    3: scissors
  strengths:
    1: 3
    2: 1
    3: 2

client:
  url: http://localhost:4200